version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: mkdirp
    versions:
    - ">= 1.a, < 2"
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - ">= 2.5.a, < 2.6"
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - ">= 2.5.a, < 2.6"
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 18.0.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.1
    - 2.42.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.18.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.30
    - 14.14.31
    - 14.14.33
    - 14.14.35
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.15.0
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
  - dependency-name: eslint-plugin-flowtype
    versions:
    - 5.2.2
    - 5.3.1
    - 5.4.0
  - dependency-name: i18next
    versions:
    - 19.8.5
    - 19.8.9
    - 19.9.0
    - 19.9.1
    - 19.9.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.17
    - 7.13.10
    - 7.13.5
    - 7.13.9
  - dependency-name: react-i18next
    versions:
    - 11.8.10
    - 11.8.7
    - 11.8.8
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.17
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.8
  - dependency-name: "@babel/eslint-parser"
    versions:
    - 7.12.17
    - 7.13.4
    - 7.13.8
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.1
    - 7.13.8
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: react-virtuoso
    versions:
    - 1.5.0
    - 1.5.10
    - 1.5.13
    - 1.5.4
    - 1.5.9
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: ts-jest
    versions:
    - 26.5.2
    - 26.5.3
  - dependency-name: "@commitlint/load"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: "@commitlint/lint"
    versions:
    - 12.0.0
  - dependency-name: stylelint
    versions:
    - 13.11.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
